apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset

spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
           - containerPort: 80
